import type { AriaRole } from 'react'
interface ConnectionProps { className: string; copyIcon: string; eyeIcon: string; eyeOffIcon: string; mobileLabel?: string; onCopy: (label: string, value: string) => void; onTogglePassword: () => void; password: string; passwordDataAttribute?: `data-${string}`; passwordVisible: boolean; remote: string; remoteIcon: string; role?: AriaRole; wanIp?: string; webIcon: string }
export function RcpcConnectionInfo({ className, copyIcon, eyeIcon, eyeOffIcon, mobileLabel, onCopy, onTogglePassword, password, passwordDataAttribute, passwordVisible, remote, remoteIcon, role, wanIp = '221.144.195.6', webIcon }: ConnectionProps) {
  const prefix = className.startsWith('mypage-home') ? 'mypage-home-rcpc' : 'rcpc-list'
  const passwordData = passwordDataAttribute ? { [passwordDataAttribute]: '' } : {}
  return <div className={`${className} rcpc-connection-info`} data-mobile-label={mobileLabel || undefined} role={role}>
    <p><b><img alt="" data-icon="web" src={webIcon} />WAN IP</b><small>{wanIp} KR</small></p>
    <p><b><img alt="" data-icon={remote.toLowerCase().startsWith('team') ? 'teamviewer' : 'anydesk'} src={remoteIcon} />{remote}</b><small><span>ID 1814706368 <button aria-label="ID 복사" className={`${prefix}__copy-button`} onClick={() => onCopy('ID', '1814706368')} type="button"><img alt="" className={`${prefix}__copy`} src={copyIcon} /></button></span>{prefix === 'rcpc-list' ? <br /> : null}<span><span {...passwordData}>PW {passwordVisible ? password : '******'}</span><span className={`${prefix}__password-actions`}><button aria-label={passwordVisible ? '비밀번호 숨기기' : '비밀번호 보기'} aria-pressed={passwordVisible} className={`${prefix}__password-toggle`} onClick={onTogglePassword} type="button"><img alt="" src={passwordVisible ? eyeOffIcon : eyeIcon} /></button><button aria-label="비밀번호 복사" className={`${prefix}__copy-button`} onClick={() => onCopy('비밀번호', password)} type="button"><img alt="" className={`${prefix}__copy`} src={copyIcon} /></button></span></span></small></p>
  </div>
}
