import { z } from 'zod'
import { productNoResponseSchema } from './productNo'
import { accountId, accountPageFields, accountPageQuery, accountTime } from './myAccountSchemas'
const amount = z.number().int().nonnegative().safe()
const text = z.string().nullable()
const time = accountTime.nullable()
export const accountOrderQuerySchema = accountPageQuery.and(z.object({ rentalStatus: z.enum(['awaiting', 'using', 'replacement_using', 'extension_waiting', 'server_ended', 'replacement_completed', 'pending_payment', 'ready', 'active', 'expiring', 'grace_period', 'access_restricted', 'expired', 'termination_pending', 'resetting', 'terminated', 'cancelled', 'refunded']).optional(), category: z.enum(['all', 'completed', 'cancelled_or_refunded']).default('all'), orderStatus: z.enum(['created', 'payment_pending', 'paid', 'cancelled', 'completed', 'refunded']).optional(), pendingPurchaseConfirmation: z.boolean().optional(), from: z.iso.date().optional(), to: z.iso.date().optional() }).refine((value) => !value.from || !value.to || value.from <= value.to))
export const accountOrderItemSchema = z.object({ orderItemId: accountId, productNo: productNoResponseSchema, title: z.string(), serverRoomName: text, categoryCode: text, categoryName: text, pcAssetId: accountId.nullable(), quantity: z.number().int().positive().max(2147483647), billingUnit: z.string(), durationUnits: z.number().int().positive().max(2147483647).nullable(), unitPrice: amount, setupFee: amount, amount, itemStatus: z.string(), serviceStartedAt: time, serviceEndsAt: time,
  rentalId: accountId.nullable(), rentalStatus: text, purchaseConfirmedAt: time, automaticConfirmationAt: time, specSummary: text, imageUrl: text, couponDiscountAmount: amount, pointUsedAmount: amount, refundPending: z.boolean(), reviewId: accountId.nullable(), expectedPoints: amount.nullable(), accruedPoints: amount.nullable(), customerRentalStatus: z.string(), instantAvailable: z.boolean() })
export type AccountOrderItem = z.infer<typeof accountOrderItemSchema>
const fields = { orderId: accountId, orderNo: z.string(), orderStatus: z.string(), paymentStatus: z.string(), paymentMethod: text, paymentRecordStatus: text, virtualAccountStatus: text, virtualAccountDepositDueAt: time, paymentTerminationReason: text, currency: z.literal('KRW'), subtotalAmount: amount, setupFeeAmount: amount, couponDiscountAmount: amount, pointUsedAmount: amount, finalAmount: amount, orderedAt: accountTime, reservationExpiresAt: time, items: z.array(accountOrderItemSchema) }
export const accountOrderPageSchema = z.object({ ...accountPageFields, items: z.array(z.object(fields)), allCount: amount, completedCount: amount, cancelledOrRefundedCount: amount })
const paymentSchema = z.object({ paymentId: accountId, method: z.string(), status: z.string(), amount, approvedAt: time, providerOrderId: text, bankName: text, accountMasked: text, depositorName: text, depositDueAt: time })
const refundSchema = z.object({ requestId: accountId, orderItemId: accountId.nullable(), method: z.string(), status: z.string(), requestedAmount: amount, requestedPointAmount: amount, approvedAmount: amount.nullable(), approvedPointAmount: amount.nullable(), restoredPoints: amount.nullable(), usedDaysDeductionRateBasisPoints: amount.nullable(), paidCash: amount, paidPoints: amount, requestedAt: accountTime, processedAt: time })
export const accountOrderDetailSchema = z.object({ ...fields, payments: z.array(paymentSchema), refunds: z.array(refundSchema), contact: z.object({ name: text, email: text, phone: text, messengerType: text, messengerId: text }).nullable() })
export type AccountOrderQuery = z.input<typeof accountOrderQuerySchema>
export type AccountOrderPage = z.infer<typeof accountOrderPageSchema>
export type AccountOrderDetail = z.infer<typeof accountOrderDetailSchema>
